<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="-1" guice-stage="DEVELOPMENT" name="Failed suite [Suite]">
  <test name="Test(failed)">
    <classes>
      <class name="com.paragon.netapp.tests.DiscoverTest">
        <methods>
          <include name="discoverManual"/>
          <include name="launchApp"/>
          <include name="Control" invocation-numbers="0"/>
          <include name="logout"/>
          <include name="discoverModule" invocation-numbers="0"/>
          <include name="DeleteWorkpack" invocation-numbers="0"/>
          <include name="launchBrowser"/>
        </methods>
      </class> <!-- com.paragon.netapp.tests.DiscoverTest -->
      <class name="com.paragon.netapp.tests.loginTest">
        <methods>
          <include name="TestCase01" invocation-numbers="0"/>
          <include name="launchApp"/>
          <include name="logout"/>
          <include name="launchBrowser"/>
        </methods>
      </class> <!-- com.paragon.netapp.tests.loginTest -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
